// Custom MO codegen Generator: inlines every .mustache file under data/templates/
// into src/render/generated/templates.ts as a TEMPLATES const, so the Cloudflare
// Worker (which has no fs access at runtime) can resolve them via the
// InMemoryProvider. The .mustache files on disk are the edit-time source of
// truth; the emitted module is the runtime source of truth.
//
// Folded from the former scripts/build-templates.ts into a Generator so the
// whole generated surface runs under one `meta gen` and is covered by the
// `meta verify --codegen` drift gate — a hand-run build step outside `meta gen`
// is invisible to the gate. See docs/how-metaobjects-is-used.md.
//
// Templates live under data/ (not metaobjects/) because loadMemory() scans
// metaobjects/ and parses everything there as metadata; non-metadata (instance
// data, mustache text) must live outside it.
//
// data/ is read relative to cwd (not ctx.projectRoot): `meta verify --codegen`
// regenerates in a temp dir holding only a copy of metaobjects/ — data/ is not
// copied there, so ctx.projectRoot would ENOENT under verify. cwd is the real
// invocation root during both `meta gen` and `meta verify`, which is exactly what
// lets the drift gate catch an un-regenerated data/templates edit.

import { readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative, sep } from "node:path";
import type { Generator, EmittedFile } from "@metaobjectsdev/codegen-ts";
import { oncePerRun } from "@metaobjectsdev/codegen-ts";

const TEMPLATES_DIR = "data/templates";

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else if (entry.endsWith(".mustache")) out.push(full);
  }
  return out;
}

export const mustacheTemplates = (): Generator => ({
  name: "mustache-templates",
  target: "render",
  generate: oncePerRun((): EmittedFile[] => {
    const files = walk(TEMPLATES_DIR).sort();
    const entries: Record<string, string> = {};
    for (const f of files) {
      // Normalise path separators to "/" so refs are stable across OSes.
      const ref = relative(TEMPLATES_DIR, f).split(sep).join("/").replace(/\.mustache$/, "");
      entries[ref] = readFileSync(f, "utf8");
    }

    const content = `// @generated by @metaobjectsdev/codegen-ts (via mustache-templates) — DO NOT EDIT.
// AUTO-GENERATED — re-run \`npm run gen:db\`.
// Source of truth: data/templates/**/*.mustache

export const TEMPLATES: Readonly<Record<string, string>> = ${JSON.stringify(entries, null, 2)} as const;
`;

    // Bare filename — the engine writes it under the "render" target's outDir.
    return [{ path: "templates.ts", content }];
  }),
});
