// Custom MO codegen Generator: emits src/personas/generated/registry.ts pairing
// each wizard instance file with its codegen'd render handles.
//
// Discovery: a "wizard" is identified by a corresponding data/wizards/<id>.yaml
// instance file. For each, the registry imports render<Id>System + render<Id>User
// from the prompt-render codegen output.
//
// Validation: if a wizard instance YAML exists with no matching template.prompt
// declarations (or vice versa), the generator throws — drift impossible.

import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { parse as parseYaml } from "yaml";
import type { Generator, EmittedFile } from "@metaobjectsdev/codegen-ts";
import { oncePerRun } from "@metaobjectsdev/codegen-ts";
import { TYPE_TEMPLATE, TEMPLATE_SUBTYPE_PROMPT } from "@metaobjectsdev/metadata";

// data/wizards is read relative to cwd (not ctx.projectRoot): `meta verify --codegen`
// regenerates in a temp dir holding only a copy of metaobjects/, so ctx.projectRoot
// would ENOENT there — cwd is the real invocation root during both gen and verify.
// (The wizard-data generator reads data/ the same way, for the same reason.)
const WIZARDS_DATA_DIR = "data/wizards";

function discoverWizardIds(): string[] {
  // Order entries by the wizard's `order` field (then id as a deterministic
  // tiebreak) so WIZARD_REGISTRY mirrors the ordering of WIZARDS. Identical
  // ordering keeps the orchestrator's iteration sequence + verdict roster
  // byte-stable across the registry and the array.
  const ids: Array<{ id: string; order: number }> = [];
  for (const f of readdirSync(WIZARDS_DATA_DIR)) {
    if (!f.endsWith(".yaml")) continue;
    const raw = readFileSync(join(WIZARDS_DATA_DIR, f), "utf8");
    const parsed = parseYaml(raw) as { id?: string; order?: number };
    const id = parsed?.id ?? f.replace(/\.yaml$/, "");
    const order = typeof parsed?.order === "number" ? parsed.order : Number.POSITIVE_INFINITY;
    ids.push({ id, order });
  }
  ids.sort((a, b) => (a.order !== b.order ? a.order - b.order : a.id.localeCompare(b.id)));
  return ids.map((x) => x.id);
}

function pascalCase(id: string): string {
  return id.charAt(0).toUpperCase() + id.slice(1);
}

export const wizardRegistry = (): Generator => ({
  name: "wizard-registry",
  target: "personas",
  generate: oncePerRun((_entities, ctx): EmittedFile[] => {
    const ids = discoverWizardIds();

    // Collect prompt declaration names from the loaded MetaRoot for cross-check.
    // template.prompt nodes are children of metadata.root. ADR-0039: resolving
    // children()/attr() by default — inheritance-proof, no own-read to justify.
    const promptNames = new Set<string>();
    for (const child of ctx.loadedRoot.children()) {
      if (child.type === TYPE_TEMPLATE && child.subType === TEMPLATE_SUBTYPE_PROMPT) {
        promptNames.add(child.name);
      }
    }

    // Cross-check: each wizard needs both system + user prompts authored.
    for (const id of ids) {
      const sysName = `${id}System`;
      const usrName = `${id}User`;
      if (!promptNames.has(sysName)) {
        throw new Error(
          `wizard-registry: data/wizards/${id}.yaml exists but template.prompt "${sysName}" is missing`,
        );
      }
      if (!promptNames.has(usrName)) {
        throw new Error(
          `wizard-registry: data/wizards/${id}.yaml exists but template.prompt "${usrName}" is missing`,
        );
      }
    }

    // Reverse cross-check: every wizard-suffixed prompt must have an instance.
    // (Verdict prompts are exempt — they don't correspond to a wizard instance.)
    for (const promptName of promptNames) {
      const m = promptName.match(/^(.+)(System|User)$/);
      if (!m) continue;
      const id = m[1];
      if (id === "verdict") continue;
      if (!ids.includes(id)) {
        throw new Error(
          `wizard-registry: template.prompt "${promptName}" exists but data/wizards/${id}.yaml is missing`,
        );
      }
    }

    const renderImports = ids
      .flatMap((id) => [`render${pascalCase(id)}System`, `render${pascalCase(id)}User`])
      .join(", ");

    const entries = ids
      .map(
        (id) =>
          `  { wizard: WIZARDS.find((w) => w.id === ${JSON.stringify(id)})!, renderSystem: render${pascalCase(id)}System, renderUser: render${pascalCase(id)}User },`,
      )
      .join("\n");

    const content = `// @generated by @metaobjectsdev/codegen-ts (via wizard-registry) — DO NOT EDIT.
// AUTO-GENERATED — re-run \`npm run gen:db\`.
// Source of truth: data/wizards/*.yaml + metaobjects/prompts/*.yaml.

import type { Wizard } from "../../db/generated/Wizard";
import type { WizardSystemPayload, WizardUserPayload } from "../../render/generated/prompts";
import type { Provider } from "@metaobjectsdev/render";
import { ${renderImports} } from "../../render/generated/prompts";
import { WIZARDS } from "./wizards";

export interface WizardRegistryEntry {
  wizard: Wizard;
  renderSystem: (p: WizardSystemPayload, provider: Provider) => string;
  renderUser: (p: WizardUserPayload, provider: Provider) => string;
}

export const WIZARD_REGISTRY: readonly WizardRegistryEntry[] = [
${entries}
];
`;

    // Bare filename — the engine writes it under the "personas" target's outDir.
    return [{ path: "registry.ts", content }];
  }),
});
