// Custom MO codegen Generator: reads data/wizards/*.yaml, validates each against
// the codegen'd Wizard Insert schema, and emits src/personas/generated/wizards.ts
// as a sorted, typed WIZARDS const array.
//
// Folded from the former scripts/build-wizard-data.ts into a Generator so wizard
// instance data is produced under one `meta gen` and covered by the drift gate.
// Validating against WizardInsertSchema (the codegen'd Zod for the Wizard entity)
// means a malformed data/wizards/*.yaml fails the build.
//
// Instance data lives under data/ (not metaobjects/) because loadMemory() treats
// everything under metaobjects/ as metadata; the wizard instance files are data.
//
// WHY data/ IS READ RELATIVE TO cwd (not ctx.projectRoot): `meta verify --codegen`
// regenerates in a temp dir containing only a copy of metaobjects/ (the metadata),
// then diffs the output against what's committed. data/ is NOT copied there, so
// reading via ctx.projectRoot would ENOENT under verify. cwd is the real invocation
// root during BOTH `meta gen` and `meta verify` — so reading data/ from cwd is what
// lets the drift gate actually catch an un-regenerated data/wizards edit. (The
// sibling wizard-registry generator reads data/ the same way, for the same reason.)
//
// INVARIANT: the validator is the *last-generated, on-disk* Wizard schema
// (src/db/generated/Wizard.ts), imported dynamically inside generate() (not at
// module top level) so config-load survives a not-yet-generated tree — the
// dependency is deferred to gen time. Because the runner defers all writes to the
// end of the run, a single commit that changes BOTH the Wizard entity schema AND a
// wizard's data validates against the prior schema and converges on the next
// `meta gen`. That's fine: the metadata is the source of truth; this Zod check is
// a build-time safety net over the instance data, not the schema authority.

import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { parse as parseYaml } from "yaml";
import type { Generator, EmittedFile } from "@metaobjectsdev/codegen-ts";
import { oncePerRun } from "@metaobjectsdev/codegen-ts";
import type { Wizard } from "../db/generated/Wizard";

const WIZARDS_DIR = "data/wizards";

async function loadWizards(): Promise<Wizard[]> {
  const { WizardInsertSchema } = await import("../db/generated/Wizard");
  const wizards: Wizard[] = [];
  for (const f of readdirSync(WIZARDS_DIR).filter((f) => f.endsWith(".yaml"))) {
    const parsed = parseYaml(readFileSync(join(WIZARDS_DIR, f), "utf8"));
    const result = WizardInsertSchema.safeParse(parsed);
    if (!result.success) {
      throw new Error(
        `wizard-data: validation failed for data/wizards/${f}:\n${JSON.stringify(result.error.format(), null, 2)}`,
      );
    }
    wizards.push(result.data as Wizard);
  }
  // Sort by `order`, then `id` as a deterministic tiebreak — byte-aligned with
  // wizard-registry-generator.ts so WIZARDS and WIZARD_REGISTRY iterate identically.
  return wizards.sort((a, b) => {
    const ao = a.order ?? Number.POSITIVE_INFINITY;
    const bo = b.order ?? Number.POSITIVE_INFINITY;
    return ao !== bo ? ao - bo : a.id.localeCompare(b.id);
  });
}

export const wizardData = (): Generator => ({
  name: "wizard-data",
  target: "personas",
  generate: oncePerRun(async (): Promise<EmittedFile[]> => {
    const wizards = await loadWizards();
    const content = `// @generated by @metaobjectsdev/codegen-ts (via wizard-data) — DO NOT EDIT.
// AUTO-GENERATED — re-run \`npm run gen:db\`.
// Source of truth: data/wizards/*.yaml

import type { Wizard } from "../../db/generated/Wizard";

export const WIZARDS: readonly Wizard[] = ${JSON.stringify(wizards, null, 2)} as const;
`;
    // Bare filename — the engine writes it under the "personas" target's outDir.
    return [{ path: "wizards.ts", content }];
  }),
});
